# Generated by Django 5.1.7 on 2025-03-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('time_slot', models.CharField(max_length=20)),
                ('class_name', models.CharField(max_length=100)),
                ('display_number', models.IntegerField(blank=True, null=True)),
                ('session_date', models.DateField(auto_now_add=True)),
                ('duration', models.IntegerField(choices=[(1, '1 minute'), (3, '3 minutes')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('csv_file', models.FileField(upload_to='timetables/')),
            ],
        ),
    ]
